spring:
  application.name: example
  threads.virtual.enabled: true
  task:
    execution:
      simple:
        concurrency-limit: 8

server:
  servlet:
    context-path: "/omer-api"
  port:
    8085


api.services:
  name: "aviation-api"
  base-url: "https://api.aviationapi.com"
